### ISSUE TITLE
Configure whether links/relations are index by rel

### ISSUE THREAD

**Issue by adrienbrault** [TheFootballSocialClub/FSCHateoasBundle#13]
The configuration would look like this:

``` yaml
fsc_hateoas:
    json:
        index_relations_by_rel: true
        index_links_by_rel: true
```
