### ISSUE TITLE
Ignore link if parameter is not null

### ISSUE THREAD

**Issue by j** [TheFootballSocialClub/FSCHateoasBundle#21]
I have the following schema:

``` yml
Path\To\My\Foo
    relations:
        - rel: self
          href:
              route: get_foo
              parameters:
                  id: .id
        - rel: bar
          href:
              route: get_bar
              parameters:
                  id: .bar.id
```

Basically, bar is not required and may be null, therefore generating the route would throw an exception.

Is there a way to only generate the `bar` link if the `foo` has resource `bar` only?  And ignore if it it does not?
